---
version: "3.2"
services:
  postgres:
    # https://hub.docker.com/_/postgres
    # docker exec -it postgres psql --username=$POSTGRES_USER --dbname=$POSTGRES_DB
    build: ./postgres
    container_name: postgres
    # exposes port 5432 by default
    expose:
      - $POSTGRES_PORT
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
